// Mocks generated by Mockito 5.2.0 from annotations
// in siex/test/features/budgets/data/budgets_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:siex/features/budgets/data/budgets_remote_data_source.dart'
    as _i2;
import 'package:siex/features/budgets/domain/entities/budget.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [BudgetsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetsRemoteDataSource extends _i1.Mock
    implements _i2.BudgetsRemoteDataSource {
  MockBudgetsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Budget>> getBudgets() =>
      (super.noSuchMethod(Invocation.method(#getBudgets, []),
              returnValue: Future<List<_i4.Budget>>.value(<_i4.Budget>[]))
          as _i3.Future<List<_i4.Budget>>);
  @override
  _i3.Future<void> updateBudget(_i4.Budget? budget) =>
      (super.noSuchMethod(Invocation.method(#updateBudget, [budget]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
