// Mocks generated by Mockito 5.2.0 from annotations
// in siex/test/features/records/presentation/records_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:siex/features/records/domain/entities/record.dart' as _i6;
import 'package:siex/features/records/domain/records_failure.dart' as _i5;
import 'package:siex/features/records/presentation/use_cases/get_new_records.dart'
    as _i3;
import 'package:siex/features/records/presentation/use_cases/get_old_records.dart'
    as _i7;
import 'package:siex/features/records/presentation/use_cases/update_records.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetNewRecords].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNewRecords extends _i1.Mock implements _i3.GetNewRecords {
  MockGetNewRecords() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.RecordsFailure, List<_i6.Record>>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
          returnValue:
              Future<_i2.Either<_i5.RecordsFailure, List<_i6.Record>>>.value(
                  _FakeEither_0<_i5.RecordsFailure, List<_i6.Record>>())) as _i4
          .Future<_i2.Either<_i5.RecordsFailure, List<_i6.Record>>>);
}

/// A class which mocks [GetOldRecords].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOldRecords extends _i1.Mock implements _i7.GetOldRecords {
  MockGetOldRecords() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.RecordsFailure, List<_i6.Record>>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
          returnValue:
              Future<_i2.Either<_i5.RecordsFailure, List<_i6.Record>>>.value(
                  _FakeEither_0<_i5.RecordsFailure, List<_i6.Record>>())) as _i4
          .Future<_i2.Either<_i5.RecordsFailure, List<_i6.Record>>>);
}

/// A class which mocks [UpdateRecords].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateRecords extends _i1.Mock implements _i8.UpdateRecords {
  MockUpdateRecords() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.RecordsFailure, void>> call(
          List<_i6.Record>? records) =>
      (super.noSuchMethod(Invocation.method(#call, [records]),
              returnValue: Future<_i2.Either<_i5.RecordsFailure, void>>.value(
                  _FakeEither_0<_i5.RecordsFailure, void>()))
          as _i4.Future<_i2.Either<_i5.RecordsFailure, void>>);
}
